// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// get_ram_usage_cpp
double get_ram_usage_cpp();
RcppExport SEXP _fmisc_get_ram_usage_cpp() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(get_ram_usage_cpp());
    return rcpp_result_gen;
END_RCPP
}
// split_vector_chunks
List split_vector_chunks(NumericVector x, int chunk_size);
RcppExport SEXP _fmisc_split_vector_chunks(SEXP xSEXP, SEXP chunk_sizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type chunk_size(chunk_sizeSEXP);
    rcpp_result_gen = Rcpp::wrap(split_vector_chunks(x, chunk_size));
    return rcpp_result_gen;
END_RCPP
}
// split_matrix_chunks
List split_matrix_chunks(NumericMatrix mat, int chunk_size);
RcppExport SEXP _fmisc_split_matrix_chunks(SEXP matSEXP, SEXP chunk_sizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type mat(matSEXP);
    Rcpp::traits::input_parameter< int >::type chunk_size(chunk_sizeSEXP);
    rcpp_result_gen = Rcpp::wrap(split_matrix_chunks(mat, chunk_size));
    return rcpp_result_gen;
END_RCPP
}
// calculate_optimal_chunk_size
int calculate_optimal_chunk_size(double data_size_mb, int total_rows, double max_ram_mb, double target_fraction);
RcppExport SEXP _fmisc_calculate_optimal_chunk_size(SEXP data_size_mbSEXP, SEXP total_rowsSEXP, SEXP max_ram_mbSEXP, SEXP target_fractionSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type data_size_mb(data_size_mbSEXP);
    Rcpp::traits::input_parameter< int >::type total_rows(total_rowsSEXP);
    Rcpp::traits::input_parameter< double >::type max_ram_mb(max_ram_mbSEXP);
    Rcpp::traits::input_parameter< double >::type target_fraction(target_fractionSEXP);
    rcpp_result_gen = Rcpp::wrap(calculate_optimal_chunk_size(data_size_mb, total_rows, max_ram_mb, target_fraction));
    return rcpp_result_gen;
END_RCPP
}
// ram_threshold_exceeded
bool ram_threshold_exceeded(double max_ram_mb);
RcppExport SEXP _fmisc_ram_threshold_exceeded(SEXP max_ram_mbSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type max_ram_mb(max_ram_mbSEXP);
    rcpp_result_gen = Rcpp::wrap(ram_threshold_exceeded(max_ram_mb));
    return rcpp_result_gen;
END_RCPP
}
// get_system_info
List get_system_info();
RcppExport SEXP _fmisc_get_system_info() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(get_system_info());
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_fmisc_get_ram_usage_cpp", (DL_FUNC) &_fmisc_get_ram_usage_cpp, 0},
    {"_fmisc_split_vector_chunks", (DL_FUNC) &_fmisc_split_vector_chunks, 2},
    {"_fmisc_split_matrix_chunks", (DL_FUNC) &_fmisc_split_matrix_chunks, 2},
    {"_fmisc_calculate_optimal_chunk_size", (DL_FUNC) &_fmisc_calculate_optimal_chunk_size, 4},
    {"_fmisc_ram_threshold_exceeded", (DL_FUNC) &_fmisc_ram_threshold_exceeded, 1},
    {"_fmisc_get_system_info", (DL_FUNC) &_fmisc_get_system_info, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_fmisc(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
