# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Get RAM Usage (Fast C++ Implementation)
#'
#' Fast implementation to get current RAM usage in MB.
#'
#' @return Numeric value representing RAM usage in MB
#' @keywords internal
get_ram_usage_cpp <- function() {
    .Call(`_fmisc_get_ram_usage_cpp`)
}

#' Fast Chunk Splitting
#'
#' Efficiently splits a numeric vector into chunks.
#'
#' @param x Numeric vector to chunk
#' @param chunk_size Size of each chunk
#' @return List of numeric vectors (chunks)
#' @keywords internal
split_vector_chunks <- function(x, chunk_size) {
    .Call(`_fmisc_split_vector_chunks`, x, chunk_size)
}

#' Fast Chunk Splitting for Matrices
#'
#' Efficiently splits a matrix into row-wise chunks.
#'
#' @param mat Numeric matrix to chunk
#' @param chunk_size Number of rows per chunk
#' @return List of numeric matrices (chunks)
#' @keywords internal
split_matrix_chunks <- function(mat, chunk_size) {
    .Call(`_fmisc_split_matrix_chunks`, mat, chunk_size)
}

#' Calculate Optimal Chunk Size
#'
#' Calculates optimal chunk size based on data size and RAM limits.
#'
#' @param data_size_mb Size of data in MB
#' @param total_rows Total number of rows
#' @param max_ram_mb Maximum RAM in MB
#' @param target_fraction Fraction of max RAM to use per chunk (default 0.1)
#' @return Optimal chunk size (number of rows)
#' @keywords internal
calculate_optimal_chunk_size <- function(data_size_mb, total_rows, max_ram_mb, target_fraction = 0.1) {
    .Call(`_fmisc_calculate_optimal_chunk_size`, data_size_mb, total_rows, max_ram_mb, target_fraction)
}

#' Monitor RAM During Processing
#'
#' Monitors RAM usage and returns true if threshold is exceeded.
#'
#' @param max_ram_mb Maximum RAM threshold in MB
#' @return Boolean indicating if RAM threshold is exceeded
#' @keywords internal
ram_threshold_exceeded <- function(max_ram_mb) {
    .Call(`_fmisc_ram_threshold_exceeded`, max_ram_mb)
}

#' Get System Information
#'
#' Returns system information including total and available RAM.
#'
#' @return List with system memory information
#' @keywords internal
get_system_info <- function() {
    .Call(`_fmisc_get_system_info`)
}

